# Generated by Django 4.2.11 on 2025-11-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_is',
            new_name='article_id',
        ),
    ]
