# Generated by Django 5.2.7 on 2025-12-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Passionate entrepreneur and business strategist. Helping startups scale through data-driven decisions and smart leadership.'),
        ),
    ]
