# Generated by Django 5.2.7 on 2025-12-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_article_likes_commentreply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
